# Your workflow name.
name: render

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2


### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Release a Docker container to Render. # Your custom step name
        uses: johnbeynon/render-deploy-action@v0.0.8 # GitHub action name (leave it as it is).
        with:
          # Below you must provide variables for your Heroku app.

          # The email address associated with your Heroku account.
          # If you don't want to use repository secrets (which is recommended) you can do:
          # email: my.email@example.com
          #github-token: ${{ secrets.RENDER_EMAIL }}
          
          # Heroku API key associated with provided user's email.
          # Api Key is available under your Heroku account settings.
          api-key: ${{ secrets.RENDER_API_KEY }}
          
          # Name of the heroku application to which the build is to be sent.
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          wait-for-succes: true
